<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
	<title>Gomoko</title>
</head>
<body>
	<form id="form1" runat="server">
	<div>
		<asp:TextBox ID="TextBox1" runat="server" OnTextChanged="TextBox1_TextChanged"></asp:TextBox>
		<asp:Label ID="Label1" runat="server" Text="Label"></asp:Label><br />
		<asp:Button ID="Button1" runat="server" Text="Button" /><br />
		<asp:Panel ID="Panel1" runat="server" Width="409px">
			<br />
		<asp:ImageButton ID="ImageButton1" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" OnClick="ImageButton1_Click" /><asp:ImageButton ID="ImageButton2" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" OnClick="ImageButton2_Click" /><asp:ImageButton ID="ImageButton3" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton4" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton5" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton6" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" OnClick="ImageButton6_Click" Width="36px" /><asp:ImageButton ID="ImageButton10" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton9" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton8" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton7" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton11" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton12" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton13" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton14" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton15" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton20" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton19" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton18" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton17" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton16" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton21" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton22" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton23" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton24" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton25" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton26" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton27" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton28" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton29" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton30" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton31" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton32" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton33" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton34" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton35" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton36" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton37" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton38" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton39" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton40" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton41" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton42" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton43" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton44" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton45" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton46" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton47" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton48" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton49" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton50" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton51" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" OnClick="ImageButton1_Click" /><asp:ImageButton ID="ImageButton52" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" OnClick="ImageButton2_Click" /><asp:ImageButton ID="ImageButton53" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton54" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton55" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton56" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" OnClick="ImageButton6_Click" Width="36px" /><asp:ImageButton ID="ImageButton57" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton58" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton59" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton60" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton61" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton62" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton63" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton64" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton65" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton66" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton67" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton68" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton69" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton70" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton71" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton72" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton73" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton74" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton75" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton76" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton77" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton78" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton79" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton80" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton81" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton82" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton83" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton84" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton85" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton86" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton87" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton88" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton89" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton90" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		<asp:ImageButton ID="ImageButton91" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton92" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton93" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton94" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton95" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton96" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton97" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton98" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton99" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><asp:ImageButton ID="ImageButton100" runat="server" Height="36px" ImageUrl="~/images/aGrid2.png" Width="36px" /><br />
		&nbsp;</asp:Panel>
	</div>
		<% new Button(); %>
	</form>
</body>
</html>
